export const TOKEN_USER = "ACCESS_TOKEN";
export const OAUTH_GOOGLE = "https://oauth2.googleapis.com/tokeninfo?id_token=";
// export const API_URL = "http://localhost:3000";
export const API_URL = "https://dinhhai-caro-server.herokuapp.com";
export const WIDTH = 20;
export const HEIGHT = 20;
export const SOCKET_FIND_PARTNER = "SOCKET_FIND_PARTNER";
export const SOCKET_RESPONSE_PARTNER = "SOCKET_RESPONSE_PARTNER";
export const SOCKET_CHAT = "SOCKET_CHAT";
export const SOCKET_CARO_ONLINE = "SOCKET_CARO_ONLINE";
